### ISSUE TITLE
Always 0

### ISSUE THREAD

**Issue by wimjongman** [KdotJPG/OpenSimplex2#21]
Why does `double noise = OpenSimplex2.noise2(seed, 0d , 0d);` always return zero no matter what the seed is?

**Comment by wimjongman** [comment]
You can probably tell I'm a noob but how can I get a random starting value when starting from 0,0? Also I noticed that I never get completely to -1 neither do I completely get to 1 even for 1000 million iterations which means I can never get close to my mapped peak values.  

<details>

```
		double smallestD = 1;
		double largestD = -1;
		int smallest = 365;
		int largest = 0;
		int div = 1;
		long seed = System.currentTimeMillis();
		for (int i = 0; i < 1000000000; i++) {
			seed = new Random().nextLong();
			double noise = OpenSimplex2.noise2(seed, 1d / div, 1d / div);
			if (largestD < noise) {
				largestD = noise;
			}
			if (smallestD > noise) {
				smallestD = noise;
			}

			int mappedValue = (int) map(noise, -1, 1, 0, 365);
			if (largest < mappedValue) {
				largest = mappedValue;
			}
			if (smallest > mappedValue) {
				smallest = mappedValue;
			}

			if (i % 100000000 == 0)
				System.out.print(".");

		}
		System.out.println("largest double  " + largestD);
		System.out.println("smallest double " + smallestD);
		System.out.println("largest mapped  " + largest);
		System.out.println("smallest mapped " + smallest);

```

largest double  0.9295401573181152
smallest double -0.9295401573181152
largest mapped  352
smallest mapped 12

**Comment by KdotJPG** [comment]
The starting point is always zero due to the nature of the simplex grid transform, which keeps (0, 0) at (0, 0), and the gradient ramps which start at zero at each vertex.

The range scaling constant was computed using [this tool](https://github.com/KdotJPG/NoiseNormalizer). It is possible for the noise to reach these values, but there are two reasons your search may not be leading you to them:

- First, there are 24³=13,824 possible gradient configurations for a given grid cell in the noise, only a handful (~6) of which may lead to a maximum or minimum being present within the cell. This means that, for a given cell that a sampling point lies in, it already has only a 1/2,304 chance of containing a coordinate that evaluates to -1 or 1.

- Second, the sampler in your technique randomizes the seed but not the coordinate, so it will not necessarily find the locations within the cells that produce the extrema. Keep in mind that, even across noise seeds, the grid is always in the same place. If you add some randomness to your coordinates -- or, better yet, follow the slope of the noise to the local min/max, then you'll get much closer to the global bounds.

**Comment by wimjongman** [comment]
Ah, understood. These are the coordinates of the internal grid, not my local coordinates. Thank you.
